name = "korant"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "METRICS_CACHE"
id = "58fcc92a0626419e884d3b7ccac19d1e"
# To create: wrangler kv:namespace create METRICS_CACHE
# Then paste the returned id above
