// ┌──────────────────────────────────────────────────────────────────────────┐
// │ REPO PATH:  app/api/whatsapp/cart-abandonment/stats/route.ts   (NEW FILE)   │
// │ Create at <repo-root>/app/api/whatsapp/cart-abandonment/stats/route.ts     │
// │                                                                            │
// │ The Cart Abandonment tab's KPIs: carts detected → per-message sent /        │
// │ recovered / revenue, plus the headline total revenue generated by this      │
// │ activity. ?month=YYYY-MM optional (defaults to all-time).                  │
// └──────────────────────────────────────────────────────────────────────────┘
export const runtime = 'edge'
import { NextRequest, NextResponse } from 'next/server'
import { getCartAbandonmentStats } from '@/lib/cart-abandonment'

export const dynamic = 'force-dynamic'

export async function GET(request: NextRequest) {
  const userId = request.headers.get('x-user-id')!
  const { searchParams } = new URL(request.url)
  const month = searchParams.get('month') || undefined
  const stats = await getCartAbandonmentStats(userId, month)
  return NextResponse.json(stats)
}
