'use client'
// ┌──────────────────────────────────────────────────────────────────────────┐
// │ REPO PATH:  components/CartAbandonmentTab.tsx   (NEW FILE)                   │
// │ Create at <repo-root>/components/CartAbandonmentTab.tsx                     │
// │                                                                            │
// │ The "Cart Abandonment" sub-tab, mounted inside WhatsAppDashboard between    │
// │ Campaigns and Templates. Two halves: (1) KPIs — carts detected → per-       │
// │ message funnel, with the headline TOTAL REVENUE generated by the activity;  │
// │ (2) the sequence builder — up to 3 steps, each with an approved template,   │
// │ a days delay, an optional coupon, and its own tracking link.               │
// │                                                                            │
// │ Styling matches the existing dashboard: inline styles + CSS vars.          │
// └──────────────────────────────────────────────────────────────────────────┘
import { useState, useEffect } from 'react'

interface Template {
  id: string; template_name: string; status: string; variable_count: number; language: string
}
interface Step {
  step_no?: number; enabled?: boolean; delay_days?: number
  template_id?: string; template_name?: string; language?: string
  variable_map?: Record<string, string>; coupon_code?: string | null
  tracking_slug?: string; tracking_link?: string
}
interface Props {
  templates: Template[]           // passed from WhatsAppDashboard (already loaded)
  month?: string
}

const VAR_OPTIONS = [
  { value: '__name__', label: 'Contact name' },
  { value: '__link__', label: 'Tracking link (auto)' },
  { value: '__code__', label: 'Coupon code (this step)' },
  { value: '__literal__', label: 'Fixed text…' },
]

export default function CartAbandonmentTab({ templates, month }: Props) {
  const approved = templates.filter(t => t.status === 'APPROVED')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')

  const [enabled, setEnabled] = useState(false)
  const [sendHour, setSendHour] = useState(10)
  const [timezone, setTimezone] = useState('Asia/Kolkata')
  const [expiryDays, setExpiryDays] = useState(14)
  const [steps, setSteps] = useState<Step[]>([])
  const [stats, setStats] = useState<any>(null)

  const load = async () => {
    setLoading(true)
    const m = month || new Date().toISOString().slice(0, 7)
    const [seqRes, statsRes] = await Promise.all([
      fetch('/api/whatsapp/cart-sequence'),
      fetch(`/api/whatsapp/cart-abandonment/stats?month=${m}`),
    ])
    const seq = await seqRes.json()
    const st = await statsRes.json()
    setEnabled(!!seq.sequence?.enabled)
    setSendHour(seq.sequence?.send_hour ?? 10)
    setTimezone(seq.sequence?.timezone || 'Asia/Kolkata')
    setExpiryDays(seq.sequence?.expiry_days ?? 14)
    setSteps((seq.steps || []).map((s: any) => ({ ...s })))
    setStats(st)
    setLoading(false)
  }
  useEffect(() => { load() /* eslint-disable-next-line */ }, [month])

  const addStep = () => {
    if (steps.length >= 3) return
    setSteps([...steps, { enabled: true, delay_days: steps.length === 0 ? 1 : 2, variable_map: {} }])
  }
  const removeStep = (i: number) => setSteps(steps.filter((_, idx) => idx !== i))
  const patchStep = (i: number, patch: Partial<Step>) =>
    setSteps(steps.map((s, idx) => idx === i ? { ...s, ...patch } : s))

  const onPickTemplate = (i: number, templateName: string) => {
    const t = approved.find(x => x.template_name === templateName)
    patchStep(i, { template_name: templateName, template_id: t?.id, language: t?.language || 'en', variable_map: {} })
  }

  const save = async () => {
    setError(''); setNotice(''); setSaving(true)
    // Guard: an enabled sequence needs at least one step with a template.
    if (enabled && (steps.length === 0 || steps.some(s => !s.template_name))) {
      setError('Every step needs an approved template before you can turn the sequence on.')
      setSaving(false); return
    }
    const res = await fetch('/api/whatsapp/cart-sequence', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        enabled, send_hour: sendHour, timezone, expiry_days: expiryDays,
        steps: steps.map((s, i) => ({
          step_no: i + 1, enabled: s.enabled !== false, delay_days: s.delay_days ?? 1,
          template_id: s.template_id, template_name: s.template_name, language: s.language || 'en',
          variable_map: s.variable_map || {}, coupon_code: s.coupon_code || null,
        })),
      }),
    })
    const json = await res.json()
    setSaving(false)
    if (!res.ok) { setError(json.error || 'Save failed'); return }
    setSteps((json.steps || []).map((s: any) => ({ ...s })))
    setNotice(json.warnings?.length ? json.warnings.join(' ') : 'Saved.')
  }

  const money = (n: number) =>
    n >= 1000 ? `₹${(n / 1000).toFixed(1)}k` : `₹${Math.round(n || 0).toLocaleString('en-IN')}`

  if (loading) return <div style={{ padding: 40, textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>Loading…</div>

  return (
    <div>
      {/* ── Headline: revenue generated by this activity ── */}
      <div style={{ display: 'flex', gap: 14, marginBottom: 18, flexWrap: 'wrap' }}>
        <div style={{ flex: '1 1 220px', background: 'var(--green-bg, rgba(37,211,102,0.08))', border: '0.5px solid var(--green)', borderRadius: 10, padding: '16px 20px' }}>
          <div style={{ fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-dim)', marginBottom: 6 }}>Revenue recovered by this activity</div>
          <div style={{ fontSize: 26, fontWeight: 600, color: 'var(--green)', lineHeight: 1 }}>{money(stats?.totalRevenue || 0)}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 6 }}>
            {stats?.recoveredByMessage || 0} carts recovered after a message
            {stats?.organicRevenue ? ` · +${money(stats.organicRevenue)} bought before any message` : ''}
          </div>
        </div>
      </div>

      {/* ── Top-line KPIs ── */}
      {(() => {
        const kpis = [
          { label: 'Carts detected', value: (stats?.detected || 0).toLocaleString('en-IN'), color: 'var(--text-primary)', sub: null as string | null },
          { label: 'Messageable', value: (stats?.messageable || 0).toLocaleString('en-IN'), color: '#53bdeb', sub: 'opted in' },
          { label: 'Recovered', value: (stats?.recovered || 0).toLocaleString('en-IN'), color: 'var(--green)', sub: `${stats?.recoveryRate || 0}%` },
          { label: 'By message', value: (stats?.recoveredByMessage || 0).toLocaleString('en-IN'), color: 'var(--amber)', sub: null },
        ]
        return (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', marginBottom: 22, marginLeft: -24, marginRight: -24, borderTop: '0.5px solid var(--border)', borderBottom: '0.5px solid var(--border)' }}>
            {kpis.map((k, i) => (
              <div key={k.label} style={{ padding: '14px 20px', borderRight: i < 3 ? '0.5px solid var(--border)' : 'none' }}>
                <div style={{ fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-dim)', marginBottom: 6 }}>{k.label}</div>
                <div style={{ fontSize: 18, fontWeight: 500, color: k.color, lineHeight: 1 }}>{k.value}</div>
                {k.sub && <div style={{ fontSize: 10, color: k.color, opacity: 0.7, marginTop: 3 }}>{k.sub}</div>}
              </div>
            ))}
          </div>
        )
      })()}

      {/* ── Per-message funnel ── */}
      <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-dim)', marginBottom: 10 }}>Which message brought them back</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12, marginBottom: 30 }}>
        {(stats?.steps || [1, 2, 3].map((n: number) => ({ step: n, sent: 0, recovered: 0, revenue: 0, recoveryRate: '0' }))).map((st: any) => (
          <div key={st.step} style={{ border: '0.5px solid var(--border)', borderRadius: 9, padding: '14px 16px' }}>
            <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-primary)', marginBottom: 10 }}>Message {st.step}</div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 6 }}>
              <span style={{ color: 'var(--text-muted)' }}>Sent</span><span style={{ color: 'var(--text-primary)' }}>{(st.sent || 0).toLocaleString('en-IN')}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 6 }}>
              <span style={{ color: 'var(--text-muted)' }}>Recovered</span><span style={{ color: 'var(--green)' }}>{(st.recovered || 0).toLocaleString('en-IN')} <span style={{ opacity: 0.6 }}>({st.recoveryRate || 0}%)</span></span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
              <span style={{ color: 'var(--text-muted)' }}>Revenue</span><span style={{ color: 'var(--amber)', fontWeight: 500 }}>{money(st.revenue || 0)}</span>
            </div>
          </div>
        ))}
      </div>

      {/* ── Sequence builder ── */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14, gap: 12, flexWrap: 'wrap' }}>
        <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--text-primary)' }}>Follow-up sequence</div>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: 'var(--text-muted)', cursor: 'pointer' }}>
          <input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} />
          {enabled ? <span style={{ color: 'var(--green)' }}>Active</span> : 'Paused'}
        </label>
      </div>

      {/* schedule controls */}
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', marginBottom: 20 }}>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>Send messages at</div>
          <select value={sendHour} onChange={e => setSendHour(Number(e.target.value))}
            style={{ background: '#0d0d0d', colorScheme: 'dark', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)' }}>
            {Array.from({ length: 24 }, (_, h) => (
              <option key={h} value={h}>{`${String(h).padStart(2, '0')}:00`}</option>
            ))}
          </select>
        </div>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>Timezone</div>
          <input value={timezone} onChange={e => setTimezone(e.target.value)}
            style={{ background: 'var(--input-bg, transparent)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)', width: 150 }} />
        </div>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>Stop chasing after (days)</div>
          <input type="number" min={1} value={expiryDays} onChange={e => setExpiryDays(Number(e.target.value))}
            style={{ background: 'var(--input-bg, transparent)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)', width: 90 }} />
        </div>
      </div>

      {/* steps */}
      {steps.map((s, i) => {
        const t = approved.find(x => x.template_name === s.template_name)
        const varCount = t?.variable_count || 0
        return (
          <div key={i} style={{ border: '0.5px solid var(--border)', borderRadius: 9, padding: 16, marginBottom: 12 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-primary)' }}>Message {i + 1}</div>
              <button onClick={() => removeStep(i)} style={{ background: 'transparent', border: 'none', color: 'var(--red)', fontSize: 11, cursor: 'pointer' }}>Remove</button>
            </div>

            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 12 }}>
              <div style={{ flex: '1 1 260px' }}>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>Template</div>
                <select value={s.template_name || ''} onChange={e => onPickTemplate(i, e.target.value)}
                  style={{ width: '100%', background: '#0d0d0d', colorScheme: 'dark', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)' }}>
                  <option value="">Choose an approved template…</option>
                  {approved.map(t => <option key={t.id} value={t.template_name}>{t.template_name}</option>)}
                </select>
                {approved.length === 0 && (
                  <div style={{ fontSize: 11, color: 'var(--amber)', marginTop: 4 }}>No approved templates yet — create one in the Templates tab and wait for Meta approval.</div>
                )}
              </div>
              <div style={{ width: 130 }}>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>{i === 0 ? 'Days after abandon' : 'Days after prev.'}</div>
                <input type="number" min={0} value={s.delay_days ?? 1} onChange={e => patchStep(i, { delay_days: Number(e.target.value) })}
                  style={{ width: '100%', background: 'var(--input-bg, transparent)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)' }} />
              </div>
              <div style={{ width: 150 }}>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 4 }}>Coupon (optional)</div>
                <input value={s.coupon_code || ''} onChange={e => patchStep(i, { coupon_code: e.target.value.toUpperCase() })} placeholder="e.g. COMEBACK10"
                  style={{ width: '100%', background: 'var(--input-bg, transparent)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '7px 10px', fontSize: 12, color: 'var(--text-primary)' }} />
              </div>
            </div>

            {/* variable mapping for the chosen template */}
            {varCount > 0 && (
              <div style={{ marginBottom: 10 }}>
                <div style={{ fontSize: 11, color: 'var(--text-dim)', marginBottom: 6 }}>Fill the template variables</div>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  {Array.from({ length: varCount }, (_, v) => {
                    const key = `{{${v + 1}}}`
                    const val = s.variable_map?.[key] || ''
                    const isLiteral = val && !VAR_OPTIONS.some(o => o.value === val)
                    return (
                      <div key={key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                        <span style={{ fontSize: 10, color: 'var(--text-dim)' }}>{key}</span>
                        <select value={isLiteral ? '__literal__' : (val || '')} onChange={e => {
                          const nv = e.target.value === '__literal__' ? ' ' : e.target.value
                          patchStep(i, { variable_map: { ...(s.variable_map || {}), [key]: nv } })
                        }} style={{ background: '#0d0d0d', colorScheme: 'dark', border: '0.5px solid var(--border)', borderRadius: 7, padding: '5px 8px', fontSize: 11, color: 'var(--text-primary)' }}>
                          <option value="">—</option>
                          {VAR_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                        </select>
                        {(isLiteral || val === ' ') && (
                          <input value={val === ' ' ? '' : val} onChange={e => patchStep(i, { variable_map: { ...(s.variable_map || {}), [key]: e.target.value || ' ' } })} placeholder="text"
                            style={{ background: 'var(--input-bg, transparent)', border: '0.5px solid var(--border)', borderRadius: 7, padding: '5px 8px', fontSize: 11, color: 'var(--text-primary)', width: 120 }} />
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>
            )}

            {s.tracking_link && (
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                Tracking link: <span style={{ color: 'var(--blue)', wordBreak: 'break-all' }}>{s.tracking_link}</span>
              </div>
            )}
          </div>
        )
      })}

      {steps.length < 3 && (
        <button onClick={addStep} style={{ border: '0.5px dashed var(--border)', background: 'transparent', color: 'var(--text-muted)', borderRadius: 8, padding: '10px 16px', fontSize: 12, cursor: 'pointer', width: '100%', marginBottom: 16 }}>
          + Add message {steps.length + 1} {steps.length === 0 ? '' : `(of 3)`}
        </button>
      )}

      {error && <div style={{ fontSize: 12, color: 'var(--red)', marginBottom: 10 }}>{error}</div>}
      {notice && <div style={{ fontSize: 12, color: 'var(--green)', marginBottom: 10 }}>{notice}</div>}

      <button onClick={save} disabled={saving}
        style={{ background: 'var(--green)', border: 'none', color: '#04120a', borderRadius: 8, padding: '9px 22px', fontSize: 13, fontWeight: 500, cursor: saving ? 'default' : 'pointer', opacity: saving ? 0.6 : 1 }}>
        {saving ? 'Saving…' : 'Save sequence'}
      </button>
    </div>
  )
}
