// ┌──────────────────────────────────────────────────────────────────────────┐
// │ REPO PATH:  app/api/analytics/cart-recovery/route.ts   (NEW FILE)           │
// │ Create at <repo-root>/app/api/analytics/cart-recovery/route.ts             │
// │                                                                            │
// │ Compact cart-recovery KPI for the overview dashboard: the headline TOTAL    │
// │ REVENUE generated by the cart-abandonment activity, plus carts recovered    │
// │ and the per-message split. Mirrors the auth/month handling of the other     │
// │ analytics routes (admin may pass ?clientId=; a client is scoped to self).  │
// └──────────────────────────────────────────────────────────────────────────┘
export const runtime = 'edge'
export const dynamic = 'force-dynamic'
import { NextRequest, NextResponse } from 'next/server'
import { getCartAbandonmentStats } from '@/lib/cart-abandonment'

export async function GET(request: NextRequest) {
  const role = request.headers.get('x-user-role')!
  const userId = request.headers.get('x-user-id')!
  const { searchParams } = new URL(request.url)
  const clientId = searchParams.get('clientId') || (role === 'client' ? userId : null)
  const month = searchParams.get('month') || new Date().toISOString().slice(0, 7)

  if (!clientId) return NextResponse.json({ error: 'clientId required' }, { status: 400 })
  if (role === 'client' && clientId !== userId) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const s = await getCartAbandonmentStats(clientId, month)
  return NextResponse.json({
    totalRevenue: s.totalRevenue,        // ⭐ revenue generated by cart-abandonment
    recovered: s.recoveredByMessage,
    detected: s.detected,
    recoveryRate: s.recoveryRate,
    byMessage: s.steps.map(st => ({ step: st.step, recovered: st.recovered, revenue: st.revenue })),
    month,
  })
}
